### ISSUE TITLE
Add "last seen/last location" statuses to robots

### ISSUE THREAD

**Issue by kvsikand** [ut-amrl/robofleet#3]
This would cause all robots ever seen by robofleet to show up on the status page

**Comment by kvsikand** [comment]
This is currently in progress in:
https://github.com/ut-amrl/robofleet_server/tree/kavan/mongo-db
and
https://github.com/ut-amrl/robofleet_webviz/tree/kavan/static-robots

@loganzartman, @joydeep-b if you feel inclined, take a look at the approach and see if it makes sense. The code isn't cleaned up/pull-request-ready yet, but it does mostly work

**Comment by joydeep-b** [comment]
Are these MongoDB connection secrets in there?
https://github.com/ut-amrl/robofleet_server/compare/kavan/mongo-db#diff-21648d6cfc264879aae2812dba24f45bR9

No secrets in the repo, please - they should be read from config.
